export const ACTIVITY_TYPES = {
  TASK_CREATED: "TASK_CREATED",

  TASK_STATUS_CHANGED:
    "TASK_STATUS_CHANGED",

  SPRINT_STARTED:
    "SPRINT_STARTED",

  SPRINT_COMPLETED:
    "SPRINT_COMPLETED",

  TASK_MOVED: "TASK_MOVED",

  TASK_ASSIGNED:
    "TASK_ASSIGNED",

  SPRINT_CREATED:
    "SPRINT_CREATED",

  MEMBER_ADDED:
    "MEMBER_ADDED",

  WORKSPACE_CREATED:
    "WORKSPACE_CREATED"
} as const;

export enum ActivityAction {
  TASK_CREATED = "TASK_CREATED",

  TASK_STATUS_CHANGED =
    "TASK_STATUS_CHANGED",

  TASK_ASSIGNED =
    "TASK_ASSIGNED",

  TASK_MOVED =
    "TASK_MOVED",

  SPRINT_CREATED =
    "SPRINT_CREATED",

  MEMBER_ADDED =
    "MEMBER_ADDED",

  WORKSPACE_CREATED =
    "WORKSPACE_CREATED",
}